Add Typing
myk-org/github-webhook-server pull request #486
Opened 2024-07-03 05:43 UTC by rnetser

2024-07-03 07:32 UTC, myakove requested changes
Can you please add mypy to pre-commit?

2024-07-03 07:32 UTC, myakove commented on webhook_server_container/libs/github_api.py
> +        self.can_be_merged_required_labels: Any
List[str]

2024-07-03 10:47 UTC, rnetser commented
/build-and-push-container

2024-07-03 10:48 UTC, rnetser commented
/build-and-push-container

2024-07-03 10:58 UTC, rnetser commented
/build-and-push-container

2024-07-03 10:59 UTC, rnetser commented
/build-and-push-container

2024-07-03 11:02 UTC, rnetser commented
/retest tox

2024-07-03 11:02 UTC, myakove commented
!

2024-07-03 11:03 UTC, myakove reviewed
!

2024-07-03 11:32 UTC, myakove commented
/build-and-push-container

2024-07-03 11:35 UTC, myakove commented
/retest tox

2024-07-03 11:35 UTC, rnetser reviewed
sasdasddsa

2024-07-03 11:40 UTC, myakove commented
/build-and-push-container

2024-07-03 11:47 UTC, rnetser reviewed
zczczxzczxczxc

2024-07-07 12:20 UTC, myakove commented
/verified

2024-07-07 12:25 UTC, myakove commented
/retest tox

2024-07-07 12:25 UTC, myakove commented
/lgtm

2024-07-07 12:26 UTC, myakove commented
/build-and-push-container

2024-07-07 12:27 UTC, myakove commented
/check-can-merge

2024-07-07 12:28 UTC, myakove commented
/lgtm cancel

2024-07-07 12:36 UTC, myakove commented
/verified

2024-07-07 12:48 UTC, myakove commented
/verified

2024-07-07 12:49 UTC, myakove approved these changes

2024-07-07 12:51 UTC, myakove commented
/check-can-merge

2024-07-07 13:16 UTC, myakove commented
/verified

2024-07-07 16:10 UTC, myakove commented
/verified cancel

2024-07-08 07:15 UTC, rnetser commented
/lgtm

2024-07-08 11:20 UTC, myakove commented
/build-and-push-container

2024-07-08 11:20 UTC, myakove commented
/verified

2024-07-08 11:30 UTC, myakove commented
/retest build-container

2024-07-08 11:31 UTC, myakove commented
/verified

2024-07-08 11:31 UTC, myakove commented
/lgtm

2024-07-08 11:32 UTC, merged